### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Yuri-Neko** [IndonesianDev/NekoBocc#6]
{
  "result": {
    "img": "https://nekopoi.care/wp-content/uploads/2023/02/ILZ56ry-204x300.jpg",
    "title": "Meijyou – NekoPoi",
    "synopsis": "Seorang laki-laki yang tergila-gila dan terobsesi dengan seorang wanita yang merupakan kakak kelas. Ia memanfaatkan kerentanannya dan membuat kesepakatan untuk menjadi wanitanya karena telah menyelamatkan pacarnya. Bagaimanakah kelanjutan hubungannya? Apakah wanita itu bisa bertahan?",
    "views": 25604,
    "japanese": "迷情",
    "category": "Hentai",
    "episode": 2,
    "status": "Ongoing",
    "aired": "Mar 01, 2021",
    "producer": "Poly Animation",
    "genre": "Big Oppai, Forced, Netorare, Schoolgirl",
    "duration": "20 min",
    "score": 6.89
  }
}

di dalam result random tambahkan url episode nya apakah bisa?

**Comment by SlavyanDesu** [comment]
bisa, nanti ku coba malem

**Comment by SlavyanDesu** [comment]
@Yuri-Neko Done.
Silakan update ke versi terbaru. Perubahan selengkapnya ada di https://github.com/SlavyanDesu/NekoBocc/compare/v1.3.5...v1.4.0
